apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextn-deployment
  labels:
    app: nextn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextn
  template:
    metadata:
      labels:
        app: nextn
    spec:
      containers:
      - name: nextn
        image: your-image-name # This will be replaced by the CI/CD pipeline
        ports:
        - containerPort: 3000