name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: "us-central1"
  CLUSTER_NAME: "nextn-cluster"
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextn:${{ github.sha }}

jobs:
  provision:
    name: "Provision Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Terraform"
        uses: "hashicorp/setup-terraform@v2"

      - name: "Initialize Terraform"
        run: terraform -chdir=terraform init

      - name: "Apply Terraform"
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var="gcp_project_id=${GCP_PROJECT_ID}" \
            -var="cluster_name=${CLUSTER_NAME}"

  build-and-deploy:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    needs: provision
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v1"
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: "us-central1-a"

      - name: "Configure Docker"
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Image
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          mage push

      - name: Deploy to GKE
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          mage deploy